# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0btasks.proto\x12\nnode_tasks"\x14\n\x04Name\x12\x0c\n\x04name\x18\x01 \x01(\t"$\n\x05Table\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\x32;\n\x06Tables\x12\x31\n\x08GetTable\x12\x10.node_tasks.Name\x1a\x11.node_tasks.Table"\x00\x42\x06\xa2\x02\x03RTGb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "tasks_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\242\002\003RTG"
    _globals["_NAME"]._serialized_start = 27
    _globals["_NAME"]._serialized_end = 47
    _globals["_TABLE"]._serialized_start = 49
    _globals["_TABLE"]._serialized_end = 85
    _globals["_TABLES"]._serialized_start = 87
    _globals["_TABLES"]._serialized_end = 146
# @@protoc_insertion_point(module_scope)
