# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import tasks_pb2 as tasks__pb2

import grpc


class TablesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTable = channel.unary_unary(
            "/node_tasks.Tables/GetTable",
            request_serializer=tasks__pb2.Name.SerializeToString,
            response_deserializer=tasks__pb2.Table.FromString,
        )


class TablesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TablesServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetTable": grpc.unary_unary_rpc_method_handler(
            servicer.GetTable,
            request_deserializer=tasks__pb2.Name.FromString,
            response_serializer=tasks__pb2.Table.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "node_tasks.Tables", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Tables(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTable(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/node_tasks.Tables/GetTable",
            tasks__pb2.Name.SerializeToString,
            tasks__pb2.Table.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
