apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: ceph-corbo-cephfs

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: ceph-corbo-cephfs

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: credentials-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: ceph-corbo-cephfs

---
